myproject/OTS/urls.py
from django.urls import path
from OTS.views import *
app_name='OTS'
urlpatterns = [
    path('',welcome),
    path('new-candidate',candidateRegistrationForm,name='registrationForm'),
    path('store-candidate',candidateRegistration,name='storeCandidate'),
    path('login',loginView,name='login'),
    path('home',candidateHome, name='home'),
    path('test-paper',testPaper,name='testPaper'),
    path('calculate-result',calculateTestResult,name='calculateTest'),
    path('test-history',testResultHistory,name='testHistory'),
    path('result',showTestResult,name='result'),
    path('logout',logoutView,name='logout'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('OTS/',include('OTS.urls')),
]

myproject/OTS/models.py
from django.db import models

class Candidate(models.Model):
    username=models.CharField(primary_key=True,max_length=20)
    password=models.CharField(null=False, max_length=20)
    name=models.CharField(null=False,max_length=30)
    test_attempted=models.IntegerField(default=0)
    points=models.FloatField(default=0.0)
class Question(models.Model):
    qid=models.BigAutoField(primary_key=True,auto_created=True)
    que=models.TextField()
    a=models.CharField(max_length=255)
    b=models.CharField(max_length=255)
    c=models.CharField(max_length=255)
    zd=models.CharField(max_length=255)
    ans=models.CharField(max_length=2)
class Result(models.Model):
    resultid=models.BigAutoField(primary_key=True,auto_created=True)
    username=models.ForeignKey(Candidate,on_delete=models.CASCADE)
    date=models.DateField(auto_now=True)
    time=models.TimeField(auto_now=True)
    attempt=models.IntegerField()
    right=models.IntegerField()
    wrong=models.IntegerField()
    points=models.FloatField()

myproject/OTS/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse,HttpResponseRedirect
from OTS.models import *
import random

def welcome(request):
    template=loader.get_template('welcome.html')
    return HttpResponse(template.render())
def candidateRegistrationForm(request):
    res=render(request,'registration_form.html')
    return res
def candidateRegistration(request):
    if request.method=='POST':
        username=request.POST['username']
        #Check if the user already exists
        if(len(Candidate.objects.filter(username=username))):
            userStatus=1
        else:
            candidate=Candidate()
            candidate.username=username
            candidate.password=request.POST['password']
            candidate.name=request.POST['name']
            candidate.save()
            userStatus=2
    else:
        userStatus=3 #Request method is not POST
    context={
        'userStatus':userStatus
    }
    res=render(request,'registration.html',context)
    return res

def loginView(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        candidate=Candidate.objects.filter(username=username,password=password)
        if len(candidate)==0:
            loginError="Invalid Username or Password"
            res=render(request,'login.html',{'loginError':loginError})
        else:
            #login Success
            request.session['username']=candidate[0].username
            request.session['name']=candidate[0].name
            res=HttpResponseRedirect("home")
    else:
        res=render(request,'login.html')
    return res
def candidateHome(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    else:
        res=render(request,'home.html')
    return res

def testPaper(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    #fetch question from database table
    n=int(request.GET['n'])
    question_pool=list(Question.objects.all())
    random.shuffle(question_pool)
    questions_list=question_pool[:n]
    context={'questions':questions_list}
    res=render(request,'test_paper.html',context)
    return res
def calculateTestResult(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    total_attempt=0
    total_right=0
    total_wrong=0
    qid_list=[]
    for k in request.POST:
        if k.startswith('qno'):
            qid_list.append(int(request.POST[k]))
    for n in qid_list:
        question=Question.objects.get(qid=n)
        try:
            if question.ans==request.POST['q'+str(n)]:
                total_right+=1
            else:
                total_wrong+=1
            total_attempt+=1
        except:
            pass
    points=(total_right-total_wrong)/len(qid_list)*10
    #store result in Result Table
    result=Result()
    result.username=Candidate.objects.get(username=request.session['username'])
    result.attempt=total_attempt
    result.right=total_right
    result.wrong=total_wrong
    result.points=points
    result.save()
    
    #update candidate table
    candidate=Candidate.objects.get(username=request.session['username'])
    candidate.test_attempted+=1
    candidate.points=(candidate.points*(candidate.test_attempted-1)+points)/candidate.test_attempted
    candidate.save()
    return HttpResponseRedirect('result')
def testResultHistory(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")

    candidate=Candidate.objects.filter(username=request.session['username'])
    results=Result.objects.filter(username_id=candidate[0].username)
    context={'candidate':candidate[0],'results':results}
    res=render(request,'candidate_history.html',context)
    return res
def showTestResult(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    #fetch latest result from Result table
    result=Result.objects.filter(resultid=Result.objects.latest('resultid').resultid,username_id=request.session['username'])
    context={'result':result}
    res=render(request,'show_result.html',context)
    return res
def logoutView(request):
    if 'name' in request.session.keys():
        del request.session['username']
        del request.session['name']
    return HttpResponseRedirect("login")

myproject/OTS/templates/candidate_history.html
{% extends 'main.html' %}

{% block title%} OTS - Candidate Result History {%endblock title%}
{% block top%}
<a href="{% url 'OTS:home' %}">Home</a>
<a href="{% url 'OTS:logout' %}">Logout</a>
{%endblock %}
{% block content %}
<h1>Your Report Card</h1>
<p>Hi <span class="special">{{candidate.name}}</span>, 
    you have attempted in total <span class="special">{{candidate.test_attempted}}</span> tests and you have scored <span class="special">{{candidate.points}}</span> on the scale of 10.</p>
<table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>
    {% for r in results%}
    <tr>
        <td>{{r.date}}</td>
        <td>{{r.time}}</td>
        <td>{{r.attempt}}</td>
        <td>{{r.right}}</td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

myproject/OTS/templates/home.html
{% extends 'main.html' %}

{% block title%} OTS - Candidate Home Page {%endblock title%}
{% block top%}
<a href="{% url 'OTS:home' %}">Home</a>
<a href="{% url 'OTS:logout' %}">Logout</a>
{%endblock %}
{% block content %}
<h1>Welcome {{request.session.name}}, to your home page</h1>
<div class="button-link">
    <a href="{% url 'OTS:testPaper' %}?n=1">Test of 1 Question</a>
</div>
<div class="button-link">
    <a href="{% url 'OTS:testPaper' %}?n=3">Test of 3 Question</a>
</div>
<div class="button-link">
    <a href="{% url 'OTS:testPaper' %}?n=5">Test of 5 Question</a>
</div>

<div class="button-link">
    <a href="{% url 'OTS:testHistory' %}">Test History</a>
</div>
{% endblock %}

myproject/OTS/templates/login.html
{% extends 'main.html' %}

{% block title%} OTS - Login Form {%endblock title%}
{% block top%}
<a href="{% url 'OTS:registrationForm' %}">Signup</a>

{%endblock %}
{% block content %}
<div class="all-forms">
    {% if loginError%}
        <div id="error">{{loginError}}</div>
    {% endif %}
    <form action="{% url 'OTS:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-unit">
            <label for="username">Username</label>
            <input type="text" name="username">
        </div>
        <div class="form-unit">
            <label for="password">Password</label>
            <input type="password" name="password">
        </div>
        <div class="form-unit">
            <input type="submit" value="Login">
            <input type="reset" value="Clear">
        </div>
    </form>
    New user<a href="{% url 'OTS:registrationForm' %}">Click Here</a>

</div>
{% endblock %}

myproject/OTS/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'theme.css' %}">
    <link rel="stylesheet" href="{% static 'formstyle.css' %}">
    <link rel="stylesheet" href="{% static 'buttonstyle.css' %}">
</head>
<body>
    <div class="top">
        <div class="sitename"><h1>Online Testing System</h1></div>
        <div class="menu">
            {% block top%} {% endblock %}
        </div>
    </div>
    <div class="content">
        {%block content%}{% endblock %}
    </div>
</body>
</html>

myproject/OTS/templates/registration.html
{% extends 'main.html' %}

{% block title%} OTS- Registration Status {%endblock title%}
{% block top%}
<a href="{% url 'OTS:registrationForm' %}">Signup</a>
<a href="{% url 'OTS:login' %}">Login</a>
{%endblock %}
{% block content %}
{% if userStatus == 1%}
    <div class="userStatus">
        Sorry, username already exists, please try different username.
        <a href="{% url 'OTS:registrationForm' %}">Back to Candidate Registration Form</a>
    </div>
{% elif userStatus == 2 %}
    <div class="userStatus">
        Congratulations!! , User created successfully
        <a href="{% url 'OTS:login' %}">Login</a>
    </div>
{% elif userStatus == 3 %}
<div class="userStatus">
    Oops!!, Improper Request
    <a href="{% url 'OTS:registrationForm' %}">Back to Candidate Registration Form</a>
</div>
{% endif%}
{% endblock %}

myproject/OTS/templates/registration_form.html
{%extends 'main.html' %}

{% block title%} OTS-Registration Form {%endblock title%}
{% block top%}

<a href="{% url 'OTS:login' %}">Login</a>
{%endblock %}
{% block content %}
<div class="all-forms">
    <form action="{% url 'OTS:storeCandidate' %}" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username">
        <label for="password">Password</label>
        <input type="password" name="password">
        <label for="name">Name</label>
        <input type="text" name="name">
        
        
        <input type="submit" value="Submit">
        <input type="reset" value="Clear">       

    </form>
    Already have an account, <a href="{% url 'OTS:login' %}">Click Here</a>
</div>
{% endblock %}

myproject/OTS/templates/show_result.html
{% extends 'main.html' %}

{% block title%}OTS - Test Result {%endblock title%}
{% block top%}
<a href="{% url 'OTS:home' %}">Home</a>
<a href="{% url 'OTS:logout' %}">Logout</a>
{%endblock %}
{% block content %}
<table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>
    {% for r in result%}
    <tr>
        <td>{{r.date}}</td>
        <td>{{r.time}}</td>
        <td>{{r.attempt}}</td>
        <td>{{r.right}}</td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

myproject/OTS/templates/test_paper.html
{% extends 'main.html' %}

{% block title%} OTS - Test Paper {%endblock title%}
{% block top%}
{%endblock %}
{% block content %}
<form action="{% url 'OTS:calculateTest' %}" method="post">
    {% csrf_token %}
    {% for question in questions %}
    <div class="question">
        <input type="hidden" name="qno{{question.qid}}" value="{{question.qid}}">
        {{question.que}}
    </div>
    <div class="options"><input type="radio" name="q{{question.qid}}" value="a">{{question.a}}</div>
    <div class="options"><input type="radio" name="q{{question.qid}}" value="b">{{question.b}}</div>
    <div class="options"><input type="radio" name="q{{question.qid}}" value="c">{{question.c}}</div>
    <div class="options"><input type="radio" name="q{{question.qid}}" value="d">{{question.d}}</div>

    {% endfor %}
    <div><input type="submit" value="Submit"></div>
</form>
{% endblock %}

myproject/OTS/templates/welcome.html
{% extends 'main.html' %}

{% block title%} Welcome to Online Testing System {%endblock title%}
{% block top%}
<a href="{% url 'OTS:registrationForm' %}">Signup</a>
<a href="{% url 'OTS:login' %}">Login</a>
{%endblock %}
{% block content %}
<p>Welcome to Online Testing System</p>
{% endblock %}